In [1]:
import numpy as np

_Turning a list into a 1D array_

In [15]:
l = [1, 2, 3, 4, 5]
print("original list:", l)
a = np.array(l)
print("One-dimensional array:", a)

original list: [1, 2, 3, 4, 5]
One-dimensional array: [1 2 3 4 5]


_Creating a 3x3 matrix_

In [19]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


_Creating array with values ranging from 12 to 38_

In [20]:
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


_Create a 2d array with 1 on the border and 0 inside_

In [22]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("only 1 on the border")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
only 1 on the border
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


_Program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements_

In [25]:
x = np.array([1,2,3], dtype=np.float64)
print("Size of th array: ", x.size)
print("Lenth of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array:", x.nbytes)

Size of th array:  3
Lenth of one array element in bytes:  8
Total bytes consumed by the elements of the array: 24
