In [8]:
import numpy as np

_Turning a list into a 1D array_

In [9]:
l = [1, 2, 3, 4, 5]
print("original list:", l)
a = np.array(l)
print("One-dimensional array:", a)

original list: [1, 2, 3, 4, 5]
One-dimensional array: [1 2 3 4 5]


_Creating a 3x3 matrix_

In [10]:
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


_Creating array with values ranging from 12 to 38_

In [11]:
x = np.arange(12,38)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


_Create a 2d array with 1 on the border and 0 inside_

In [12]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("only 1 on the border")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
only 1 on the border
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


_Program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements_

In [13]:
x = np.array([1,2,3], dtype=np.float64)
print("Size of th array: ", x.size)
print("Lenth of one array element in bytes: ", x.itemsize)
print("Total bytes consumed by the elements of the array:", x.nbytes)

Size of th array:  3
Lenth of one array element in bytes:  8
Total bytes consumed by the elements of the array: 24


_Program to change the dimension of an array from 6 rows 0 columns to 3 rows 3 columns._

In [22]:
x = np.array([1,2,3,4,5,6,7,8,9])
print("6 rows and 0 columns")
print(x.shape)

y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3 rows and 3 columns")
print(y)

x = np.array([1,2,3,4,5,6,7,8,9])
print("change array shape to (3,3)")
x.shape = (3, 3)
print(x)

             

6 rows and 0 columns
(9,)
3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]
change array shape to (3,3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


_Program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive_

In [26]:
x = np.logspace(2., 5., 20, endpoint=False)
print(x)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


In [27]:
x = np.logspace(2., 5., 20, endpoint=True)
print(x)

[   100.            143.84498883    206.91380811    297.63514416
    428.13323987    615.84821107    885.86679041   1274.2749857
   1832.98071083   2636.65089873   3792.69019073   5455.59478117
   7847.59970351  11288.37891685  16237.76739189  23357.2146909
  33598.18286284  48329.30238572  69519.27961776 100000.        ]


_Program to collapse a 3-D array into one dimension array_