In [34]:
import pygadgetreader as pyg
import numpy as np


In [44]:
part_halo =pyg.readrockstar("../sims/MW_LMC_sim_111", "particles")
#number of particles in halo

In [45]:
np.array(part_halo)

array([], shape=(0, 2), dtype=int64)

In [22]:
part_bulge= pyg.readheader("../sims/MW_LMC_sim_111", "bulgecount")
#number of particles in bulge

In [23]:
np.float(part_bulge)

8900.0

In [24]:
part_disk= pyg.readheader("../sims/MW_LMC_sim_111", "diskcount")
#number of particles in disk


In [25]:
np.float(part_bulge)

8900.0

In [26]:
part_dm= pyg.readheader("../sims/MW_LMC_sim_111", "dmcount")

In [27]:
np.float(part_dm)

1208334.0

In [28]:
dm_vel = pyg.readsnap("../sims/MW_LMC_sim_111", "vel", "dm")

Returning DM    Velocities


In [29]:
np.array(dm_vel)

array([[-212.43364 ,  -31.829447,  -11.889923],
       [ 105.34052 ,   35.83782 , -119.942764],
       [ -10.747493,  118.32208 ,   68.07754 ],
       ...,
       [ 168.6689  ,  -19.145933,   40.38835 ],
       [  43.806034,  226.3065  , -101.70848 ],
       [  91.618614,  -65.78436 ,  -47.639122]], dtype=float32)

In [30]:
bulge_vel = pyg.readsnap("../sims/MW_LMC_sim_111", "vel", "bulge")

Returning BULGE Velocities


In [31]:
np.array(bulge_vel)

array([[-213.448   ,   87.78132 ,  125.32139 ],
       [ 106.78289 ,   -7.895038,  -92.75493 ],
       [ -30.392382,   28.04451 ,  230.20142 ],
       ...,
       [-144.54672 ,  247.72433 ,  -91.6697  ],
       [ 123.51479 ,  -60.32487 ,   35.14846 ],
       [ 125.3556  ,  132.78345 , -123.30189 ]], dtype=float32)

In [32]:
pos_disk= pyg.readsnap("../sims/MW_LMC_sim_111", "pos", "disk")

Returning DISK  Positions


In [33]:
np.shape(pos_disk)

(36700, 3)

In [46]:
xpos_disk= pos_disk[:,0]

In [48]:
np.array(xpos_disk)

array([ 6.124474 ,  5.592434 ,  6.092386 , ..., -8.394399 , -7.2372136,
       -7.4909873], dtype=float32)

In [49]:
ypos_disk= pos_disk[:,1]

In [50]:
np.array(ypos_disk)

array([55.299248, 55.470325, 55.717335, ..., 41.259357, 40.923126,
       40.652657], dtype=float32)

In [51]:
zpos_disk= pos_disk[:,2]

In [52]:
np.array(zpos_disk)

array([5.228483, 5.365698, 5.395017, ..., 5.68686 , 6.206847, 6.389599],
      dtype=float32)

In [53]:
mag_pos_disk = np.sqrt(xpos_disk**2 + ypos_disk**2 + zpos_disk**2)

In [56]:
np.array(mag_pos_disk) #magnitude position disk

array([55.882492, 56.009136, 56.30848 , ..., 42.48695 , 42.019096,
       41.827984], dtype=float32)

In [57]:
pos_bulge= pyg.readsnap("../sims/MW_LMC_sim_111", "pos", "bulge")

Returning BULGE Positions


In [58]:
np.shape(pos_bulge)

(8900, 3)

In [59]:
xpos_bulge= pos_bulge[:,0]

In [60]:
np.array(xpos_bulge)

array([  9.394648  ,  13.585126  ,  11.5615    , ...,   0.05802463,
         2.2174165 , -12.469192  ], dtype=float32)

In [61]:
ypos_bulge= pos_bulge[:,1]

In [62]:
np.array(ypos_bulge)

array([ 90.59938 ,  52.677425,  54.378178, ...,  68.93861 ,  70.545334,
       104.55884 ], dtype=float32)

In [63]:
zpos_bulge= pos_bulge[:,2]

In [64]:
np.array(zpos_bulge)

array([-1.4605405, -2.3993232, -1.0640502, ..., 26.24558  , 23.052423 ,
       -2.018742 ], dtype=float32)

In [65]:
mag_pos_bulge= np.sqrt(xpos_bulge**2 + ypos_bulge**2 + zpos_bulge**2)

In [66]:
np.array(mag_pos_bulge) #magnitude position bulge

array([ 91.09688 ,  54.45387 ,  55.603836, ...,  73.76561 ,  74.24941 ,
       105.31907 ], dtype=float32)

In [67]:
pos_dm= pyg.readsnap("../sims/MW_LMC_sim_111", "pos", "dm")

Returning DM    Positions


In [68]:
np.shape(pos_dm) 

(1208334, 3)

In [69]:
xpos_dm = pos_dm[:,0]

In [70]:
np.array(xpos_dm)

array([ 51.741066,  54.779186,  56.549335, ..., -77.343185, -76.78244 ,
       -79.0482  ], dtype=float32)

In [72]:
ypos_dm= pos_dm[:,1]

In [73]:
np.array(ypos_dm)

array([-7.521392 , -7.6233582, -5.2954745, ..., 56.14169  , 55.130196 ,
       52.321247 ], dtype=float32)

In [74]:
zpos_dm= pos_dm[:,2]

In [75]:
np.array(zpos_dm)

array([-66.452805, -66.491005, -64.05488 , ...,  77.612175,  77.38519 ,
        80.3729  ], dtype=float32)

In [76]:
mag_pos_dm= np.sqrt(xpos_dm**2 + ypos_dm**2 + zpos_dm**2)

In [78]:
np.array(mag_pos_dm) #magnitude position DM

array([ 84.55581,  86.48658,  85.60897, ..., 123.11583, 122.16116,
       124.28167], dtype=float32)